### ISSUE TITLE
Please add an RSS or Atom feed to your blog

### ISSUE THREAD

**Issue by alexott** [redefine-io/redefine-io.github.io#8]
Hello

I've found your [blog post about Clojure](https://redefine.io/blog/buffered-sequences/) and want to add the blog to the [Planet Clojure](https://planet.clojure.in/), but I can't find an RSS or Atom feed.  

Would it be possible to add an RSS or Atom feed?

**Comment by brandonstubbs** [comment]
Hello

Most certainly, we have added it: https://redefine.io/rss.xml

Our blog will have some Clojure pieces but there will also be a lot of material that relates to Cloud, Data Analytics & Datalakes.

Do you need us to provide you with a feed with only the Clojure-related content? i.e something like: https://redefine.io/blog/category/clojure/rss.xml

**Comment by alexott** [comment]
Thank you. Separate category isn’t strictly necessary, as I can filter it on the planet side - there are a lot of blogs without categories

**Comment by brandonstubbs** [comment]
Ok great, will keep it as is for now. Have a great rest of your week
